dist: trusty
language: rust
cache: cargo
rust:
  - stable
os:
  - linux
before_install:
  - sudo apt-get update -q
  - sudo apt-get install ruby ruby-dev rubygems-integration build-essential
  - gem install --no-ri --no-rdoc fpm
before_script:
  - rustup component add rustfmt-preview
script:
  - |
    if [ "$TRAVIS_BRANCH" == "master" ]; then
      cargo build --release
    else
      cargo update
      cargo fmt --all -- --write-mode=diff
      cargo build
    fi
after_script:
  - |
    if [ "$TRAVIS_BRANCH" == "master" ]; then
      ./build_apk.sh
    fi
