sudo: required
dist: trusty
language: rust
services: docker
cache: cargo

rust:
  - stable
os:
  - linux

before_install:
  - source ~/.cargo/env || true
  - rustup self update
  - sudo apt-get update -q
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

install:
  - cargo install --force cross
  - rustup component add rustfmt-preview
  - sudo apt-get install ruby ruby-dev rubygems-integration build-essential
  - gem install --no-ri --no-rdoc fpm

script:
  - |
    if [ "$TRAVIS_BRANCH" == "feature/apk-package" ]; then
      cross build --release --target x86_64-unknown-linux-musl
    else
      cargo update
      cargo fmt --all -- --write-mode=diff
      cargo build
    fi

after_script:
  - |
    if [ "$TRAVIS_BRANCH" == "feature/apk-package" ]; then
      sh ci/build_apk.sh
    fi
