dist: trusty
language: rust
cache: cargo
rust:
  - stable
os:
  - linux
before_install:
  - sudo apt-get update -q
  - sudo apt-get install ruby ruby-dev rubygems-integration build-essential
  - sudo apt-get install musl musl-tools
  - gem install --no-ri --no-rdoc fpm
before_script:
  - rustup component add rustfmt-preview
  - rustup target add x86_64-unknown-linux-musl
script:
  - |
    if [ "$TRAVIS_BRANCH" == "feature/apk-package" ]; then
      PKG_CONFIG_ALLOW_CROSS=1 cargo build --release --target x86_64-unknown-linux-musl
    else
      cargo update
      cargo fmt --all -- --write-mode=diff
      cargo build
    fi
after_script:
  - |
    if [ "$TRAVIS_BRANCH" == "master" ]; then
      ./build_apk.sh
    fi
